name: gab2020-web-ci	 

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
 	buildJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 	  
    - name: Setup .NET Core SDK
    - uses: actions/setup-dotnet@v1.4.0
    with:
    dotnet-version: 3.1.101
    - run: dotnet build -c Release
    - run: dotnet test -c Release
    - run: dotnet publish -c Release -o gab2020-web
